apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-app-deployment
  labels:
    app: model-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-app
  template:
    metadata:
      labels:
        app: model-app
    spec:
      containers:
      - name: model-app
        image: saurabh1354/llm_bert_app:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: model-container-pvc
          mountPath: /code/models
      volumes:
      - name: model-container-pvc
        persistentVolumeClaim:
          claimName: model-nfs-pvc
