apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-nfs-server
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 64Gi
  nfs:
    path: /share
    server: 34.133.52.22