apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.serverName }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.volume.storage }}
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.externalIP }}